app:
  build: .
  command: python -u run.py
  ports:
    - "5000:5000"
  volumes:
    - .:/run
  links:
    - db
db:
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=taskManager

  ports:
    - 27017:27017
